// Official iRacing Track List (iracing.com/tracks, March 2026)
// cats: array of track types. configs: number of configurations (null=unknown). free: included with membership.
const DEFAULT_TRACKS = [
  { name: "Adelaide Street Circuit", cats: ["road"], configs: null, free: false },
  { name: "Algarve International Circuit", cats: ["road"], configs: null, free: false },
  { name: "Auto Club Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Autodromo Internazionale del Mugello", cats: ["road"], configs: null, free: false },
  { name: "Autódromo Hermanos Rodriguez", cats: ["road"], configs: null, free: false },
  { name: "Autódromo Internazionale Enzo e Dino Ferrari", cats: ["road"], configs: null, free: false },
  { name: "Autódromo José Carlos Pace", cats: ["road"], configs: null, free: false },
  { name: "Autódromo Nazionale Monza", cats: ["road"], configs: null, free: false },
  { name: "Barber Motorsports Park", cats: ["road"], configs: null, free: false },
  { name: "Bark River International Raceway", cats: ["dirt-road"], configs: null, free: false },
  { name: "Brands Hatch Circuit", cats: ["road"], configs: null, free: false },
  { name: "Bristol Motor Speedway", cats: ["oval", "dirt-oval"], configs: null, free: false },
  { name: "Cadwell Park Circuit", cats: ["road"], configs: null, free: false },
  { name: "Canadian Tire Motorsport Park", cats: ["road"], configs: null, free: false },
  { name: "Cedar Lake Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Centripetal Circuit", cats: ["road"], configs: null, free: true },
  { name: "Charlotte Motor Speedway", cats: ["oval", "road"], configs: null, free: true },
  { name: "Chicago Street Course", cats: ["road"], configs: null, free: false },
  { name: "Chicagoland Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Chili Bowl", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Circuit Gilles Villeneuve", cats: ["road"], configs: null, free: false },
  { name: "Circuit Park Zandvoort", cats: ["road"], configs: null, free: false },
  { name: "Circuit Zolder", cats: ["road"], configs: null, free: false },
  { name: "Circuit de Barcelona-Catalunya", cats: ["road"], configs: null, free: false },
  { name: "Circuit de Lédenon", cats: ["road"], configs: null, free: true },
  { name: "Circuit de Nevers Magny-Cours", cats: ["road"], configs: null, free: false },
  { name: "Circuit de Spa-Francorchamps", cats: ["road"], configs: null, free: false },
  { name: "Circuit des 24 Heures du Mans", cats: ["road"], configs: null, free: false },
  { name: "Circuit of the Americas", cats: ["road"], configs: null, free: false },
  { name: "Circuito de Jerez – Ángel Nieto", cats: ["road"], configs: null, free: false },
  { name: "Circuito de Navarra", cats: ["road"], configs: null, free: true },
  { name: "Concord Speedway", cats: ["oval"], configs: null, free: true },
  { name: "Crandon International Raceway", cats: ["dirt-road"], configs: null, free: false },
  { name: "Darlington Raceway", cats: ["oval"], configs: null, free: false },
  { name: "Daytona International Speedway", cats: ["oval", "road", "dirt-road"], configs: null, free: false },
  { name: "Daytona International Speedway – Rallycross", cats: ["dirt-road"], configs: null, free: false },
  { name: "Detroit Grand Prix at Belle Isle", cats: ["road"], configs: null, free: false },
  { name: "Donington Park Racing Circuit", cats: ["road"], configs: null, free: false },
  { name: "Dover Motor Speedway", cats: ["oval"], configs: null, free: false },
  { name: "EchoPark Speedway (Atlanta)", cats: ["oval"], configs: null, free: false },
  { name: "Eldora Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Fairbury Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Federated Auto Parts Raceway at I-55", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Firebird Motorsports Park", cats: ["dirt-road"], configs: null, free: false },
  { name: "Five Flags Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Fuji International Speedway", cats: ["road"], configs: null, free: false },
  { name: "Hickory Motor Speedway", cats: ["oval"], configs: null, free: false },
  { name: "HockenheimRing", cats: ["road"], configs: null, free: false },
  { name: "Homestead Miami Speedway", cats: ["oval", "road"], configs: null, free: false },
  { name: "Hungaroring", cats: ["road"], configs: null, free: false },
  { name: "Huset's Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Indianapolis Motor Speedway", cats: ["oval", "road"], configs: null, free: false },
  { name: "Iowa Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Irwindale Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Kansas Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Kentucky Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Kevin Harvick's Kern Raceway", cats: ["oval"], configs: null, free: false },
  { name: "Knockhill Racing Circuit", cats: ["road", "dirt-road"], configs: null, free: false },
  { name: "Knoxville Raceway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Kokomo Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "LA Coliseum", cats: ["oval"], configs: null, free: false },
  { name: "Langley Speedway", cats: ["oval"], configs: null, free: true },
  { name: "Lanier National Speedway", cats: ["oval"], configs: null, free: true },
  { name: "Lanier National Speedway – Dirt", cats: ["dirt-oval"], configs: null, free: true },
  { name: "Las Vegas Motor Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Lernerville Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Limaland Motorsports Park", cats: ["dirt-oval"], configs: null, free: true },
  { name: "Lime Rock Park", cats: ["road"], configs: null, free: true },
  { name: "Lincoln Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Long Beach Street Circuit", cats: ["road"], configs: null, free: false },
  { name: "Lucas Oil Indianapolis Raceway Park", cats: ["oval", "road"], configs: null, free: false },
  { name: "Lucas Oil Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Lånkebanen (HellRX)", cats: ["dirt-road"], configs: null, free: false },
  { name: "Martinsville Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Miami International Autodrome", cats: ["road"], configs: null, free: false },
  { name: "Michelin Raceway Road Atlanta", cats: ["road"], configs: null, free: false },
  { name: "Michigan International Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Michigan International Speedway – 2009", cats: ["oval"], configs: null, free: false },
  { name: "Mid-Ohio Sports Car Course", cats: ["road"], configs: null, free: false },
  { name: "Millbridge Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Misano World Circuit Marco Simoncelli", cats: ["road"], configs: null, free: false },
  { name: "Mobility Resort Motegi", cats: ["road"], configs: null, free: false },
  { name: "MotorLand Aragón", cats: ["road"], configs: null, free: false },
  { name: "Motorsport Arena Oschersleben", cats: ["road"], configs: null, free: true },
  { name: "Mount Panorama Circuit", cats: ["road"], configs: null, free: false },
  { name: "Mount Washington Auto Road", cats: ["road"], configs: null, free: false },
  { name: "Myrtle Beach Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Nashville Fairgrounds Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Nashville Superspeedway", cats: ["oval"], configs: null, free: false },
  { name: "New Hampshire Motor Speedway", cats: ["oval", "road"], configs: null, free: false },
  { name: "New Jersey Motorsports Park", cats: ["road"], configs: null, free: false },
  { name: "New Smyrna Speedway", cats: ["oval"], configs: null, free: false },
  { name: "North Wilkesboro Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Nürburgring Grand-Prix-Strecke", cats: ["road"], configs: null, free: false },
  { name: "Nürburgring Nordschleife", cats: ["road"], configs: null, free: false },
  { name: "Okayama International Circuit", cats: ["road"], configs: null, free: true },
  { name: "Oran Park Raceway", cats: ["road"], configs: null, free: true },
  { name: "Oswego Speedway", cats: ["oval", "dirt-oval"], configs: null, free: false },
  { name: "Oulton Park Circuit", cats: ["road"], configs: null, free: true },
  { name: "Oxford Plains Speedway", cats: ["oval"], configs: null, free: true },
  { name: "Phillip Island Circuit", cats: ["road"], configs: null, free: false },
  { name: "Phoenix Raceway", cats: ["oval"], configs: null, free: false },
  { name: "Phoenix Raceway – 2008", cats: ["oval"], configs: null, free: true },
  { name: "Pocono Raceway", cats: ["oval"], configs: null, free: false },
  { name: "Pocono Raceway – 2009", cats: ["oval"], configs: null, free: false },
  { name: "Port Royal Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Portland International Raceway", cats: ["road"], configs: null, free: false },
  { name: "Red Bull Ring – Spielberg", cats: ["road"], configs: null, free: false },
  { name: "Richmond Raceway", cats: ["oval"], configs: null, free: false },
  { name: "Road America", cats: ["road"], configs: null, free: false },
  { name: "Rockingham Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Rudskogen Motorsenter", cats: ["road", "dirt-road"], configs: null, free: false },
  { name: "Sachsenring", cats: ["road"], configs: null, free: false },
  { name: "Sandown International Motor Raceway", cats: ["road"], configs: null, free: false },
  { name: "Sebring International Raceway", cats: ["road"], configs: null, free: false },
  { name: "Shell V-Power Motorsports Park at The Bend", cats: ["road"], configs: null, free: false },
  { name: "Silverstone Circuit", cats: ["road"], configs: null, free: false },
  { name: "Silverstone Circuit – 2008", cats: ["road"], configs: null, free: false },
  { name: "Slinger Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Snetterton Circuit", cats: ["road"], configs: null, free: true },
  { name: "Sonoma Raceway", cats: ["road", "dirt-road"], configs: null, free: false },
  { name: "South Boston Speedway", cats: ["oval"], configs: null, free: true },
  { name: "Southern National Motorsports Park", cats: ["oval"], configs: null, free: true },
  { name: "Stafford Motor Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Summit Point Motorsports Park", cats: ["road"], configs: null, free: true },
  { name: "Suzuka International Racing Course", cats: ["road"], configs: null, free: false },
  { name: "Talladega Superspeedway", cats: ["oval"], configs: null, free: false },
  { name: "Texas Motor Speedway", cats: ["oval"], configs: null, free: false },
  { name: "Texas Motor Speedway – 2009", cats: ["oval"], configs: null, free: false },
  { name: "The Bullring at LVMS", cats: ["oval"], configs: null, free: false },
  { name: "The Dirt Track at Charlotte", cats: ["dirt-oval"], configs: null, free: false },
  { name: "The Milwaukee Mile", cats: ["oval"], configs: null, free: false },
  { name: "Thompson Speedway Motorsports Park", cats: ["oval"], configs: null, free: true },
  { name: "Thruxton Circuit", cats: ["road"], configs: null, free: false },
  { name: "Tsukuba Circuit", cats: ["road"], configs: null, free: true },
  { name: "USA International Speedway", cats: ["oval"], configs: null, free: true },
  { name: "USA International Speedway – Dirt", cats: ["dirt-oval"], configs: null, free: true },
  { name: "Virginia International Raceway", cats: ["road"], configs: null, free: true },
  { name: "Volusia Speedway Park", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Watkins Glen International", cats: ["road"], configs: null, free: false },
  { name: "WeatherTech Raceway Laguna Seca", cats: ["road"], configs: null, free: false },
  { name: "Weedsport Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Wild West Motorsports Park", cats: ["dirt-road"], configs: null, free: false },
  { name: "Williams Grove Speedway", cats: ["dirt-oval"], configs: null, free: false },
  { name: "Willow Springs Raceway", cats: ["road"], configs: null, free: false },
  { name: "Winton Motor Raceway", cats: ["road"], configs: null, free: true },
  { name: "World Wide Technology Raceway (Gateway)", cats: ["oval", "road"], configs: null, free: false },
  { name: "iRacing Superspeedway", cats: ["oval"], configs: null, free: true },
];

export default DEFAULT_TRACKS;

// Normalize old data formats
export function normalizeTracks(tracks) {
  return tracks.map(t => ({
    ...t,
    cats: t.cats || (t.cat ? [t.cat] : ["road"]),
    configs: t.configs ?? null,
    free: !!t.free,
  }));
}
